# Generated by Django 2.1.3 on 2019-01-03 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='content',
        ),
        migrations.AddField(
            model_name='guide',
            name='content_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='content_md',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='parent_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guides.Tag'),
        ),
    ]
