# Generated by Django 2.1.5 on 2019-01-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_auto_20190102_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.ImageField(default=2, upload_to='guides/tags/'),
            preserve_default=False,
        ),
    ]
