# Generated by Django 2.1.7 on 2019-04-09 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0004_tag_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='image',
        ),
    ]
