# Generated by Django 2.1.7 on 2019-04-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0005_remove_tag_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.CharField(max_length=20),
        ),
    ]
