# Generated by Django 2.1.3 on 2018-11-13 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('proficiency', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Computer Skill',
                'verbose_name_plural': 'Computer Skills',
            },
        ),
        migrations.CreateModel(
            name='EducationExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('institution', models.CharField(max_length=140)),
                ('accreditation', models.CharField(max_length=140)),
            ],
            options={
                'verbose_name': 'Education Credibility',
                'verbose_name_plural': "Educational Credibility's",
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=140)),
                ('province', models.CharField(max_length=140)),
                ('country', models.CharField(max_length=140)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ('country', 'province', 'city'),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Resume Skill',
                'verbose_name_plural': 'Resume Skills',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=140)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ('content_type',),
            },
        ),
        migrations.CreateModel(
            name='VolunteerExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('recipient', models.CharField(max_length=140)),
                ('location',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.Location')),
            ],
            options={
                'verbose_name': 'Volunteer Experience',
                'verbose_name_plural': 'Volunteer Experiences',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('position', models.CharField(max_length=140)),
                ('employer', models.CharField(max_length=140)),
                ('location',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.Location')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
            },
        ),
        migrations.AddField(
            model_name='educationexperience',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.Location'),
        ),
    ]
