# Generated by Django 2.1.3 on 2018-11-14 18:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('_content_type',), 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='content_type',
            new_name='_content_type',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='object_id',
            new_name='_object_id',
        ),
    ]
