# Generated by Django 2.1.3 on 2018-11-25 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20181114_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationexperience',
            options={'verbose_name': 'Educational Credibility', 'verbose_name_plural': "Educational Credibility's"},
        ),
    ]
