# Generated by Django 2.1.3 on 2018-11-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('resume', '0003_auto_20181125_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.CharField(max_length=140),
        ),
    ]
