# Generated by Django 2.1.3 on 2018-11-27 21:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('resume', '0006_auto_20181127_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('content_type',), 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='_content_type',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='_object_id',
            new_name='object_id',
        ),
    ]
