# Generated by Django 2.1.3 on 2018-12-31 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20181127_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='content_type',
        ),
        migrations.AlterModelOptions(
            name='computerskill',
            options={'ordering': ('-proficiency',), 'verbose_name': 'Computer Skill', 'verbose_name_plural': 'Computer Skills'},
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
