# Generated by Django 2.1.7 on 2019-03-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_computerskill_parent_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerskill',
            name='colour',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
